server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.15.251:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverZone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      pool-name: DataHikaricP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 3000
      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.example.server.pojo
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    com.example.server.mapper: debug