server:
  port: 8082

spring:
  mail:
    #邮件服务器地址
    host: smtp.qq.com
    #协议
    protocol: smtp
    #编码格式
    default-encoding: UTF-8
    #授权码在邮件开通服务时获取
    password: bvtpswwamfuqbegf
    #发送者邮箱地址
    username: 925182704@qq.com
    #端口号
    port: 25

  rabbitmq:
    username: guest
    password: guest
    host: 172.81.205.117
    port: 5672
    listener:
      simple:
        #开启手动确认
        acknowledge-mode: manual

  redis:
    #超时时间
    timeout: 10000ms
    #服务器地址
    host: 172.81.205.117
    #服务器端口
    port: 6379
    #数据库
    database: 0
    #免密无需设置密码
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大连接阻塞时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 0
    password: 123456
